# Generated by Django 2.1 on 2018-11-05 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad_Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_actividad', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_entrega', models.DateTimeField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Avances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_avance', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_entrega', models.DateTimeField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cargo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresas', models.CharField(max_length=40)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_personal', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Cargos')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Estados')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto_Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('nombre_personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Personal')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto_Lider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('nombre_personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Personal')),
            ],
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Estados')),
            ],
        ),
        migrations.CreateModel(
            name='Reunione_Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('nombre_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Reunione_Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('nombre_personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Personal')),
            ],
        ),
        migrations.CreateModel(
            name='Reuniones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_reunion', models.CharField(max_length=40)),
                ('lugar', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_reunion', models.DateTimeField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('nombre_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Proyectos')),
            ],
        ),
        migrations.CreateModel(
            name='Sexos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='reunione_personal',
            name='nombre_reunion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Reuniones'),
        ),
        migrations.AddField(
            model_name='reunione_cliente',
            name='nombre_reunion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Reuniones'),
        ),
        migrations.AddField(
            model_name='proyecto_lider',
            name='nombre_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Proyectos'),
        ),
        migrations.AddField(
            model_name='proyecto_empleado',
            name='nombre_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Proyectos'),
        ),
        migrations.AddField(
            model_name='personal',
            name='sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Sexos'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Empresas'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Sexos'),
        ),
        migrations.AddField(
            model_name='avances',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Estados'),
        ),
        migrations.AddField(
            model_name='avances',
            name='nombre_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Proyectos'),
        ),
        migrations.AddField(
            model_name='actividades',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Estados'),
        ),
        migrations.AddField(
            model_name='actividades',
            name='nombre_avance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Avances'),
        ),
        migrations.AddField(
            model_name='actividad_personal',
            name='nombre_actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Actividades'),
        ),
        migrations.AddField(
            model_name='actividad_personal',
            name='nombre_personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Personal'),
        ),
    ]
