# Generated by Django 2.1 on 2018-11-05 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0002_auto_20181105_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='estado',
        ),
    ]
